### ISSUE TITLE
Creating Interface No Longer Works

### ISSUE THREAD

**Issue by dsm0880** [SteveCurran/vscode-spremoteapi#1]
I tried using this today and realized I could not create an SPListItemCollection Interface. Not sure if this broke with a VSCode update. I'm currently running 1.10.

**Comment by SteveCurran** [comment]
Yes it looks like 1.10.1 broke it. I will look at it tomorrow, thanks for logging the issue.

**Comment by SteveCurran** [comment]
Ok the URI argument passed into the OpenTextDocument call in VSCode is forced into lower case which caused all the problems. Not sure why they changed this. This is now fixed with 1.5.2 in the market place.
